create table tb_product
(
    id               bigint generated by default as identity,
    active            boolean,
    color              varchar(255),
    creation_date timestamp,
    update_date     timestamp not null,
    model           varchar(255),
    number           integer,
    price            decimal(19, 2),
    primary key (id)
)